imports: 
  - { resource: ./shared.yaml }
  - { resource: ./feed.yaml }

services:

  Apps.cms.controllers.status.StatusGetController:
    class: ../../controllers/status/StatusGetController
    arguments: []